### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by panenka** [samhstein/sp108e_ws2815#10]
I'm sorry. I have SP108E V2. It is working with LED shop application. I've been tried to add all 10 files into folder to HA and add into config these lines 

```
# led strip
light:
  - platform: sp108e_ws2815
    host: 192.168.15.162
    name: 'sp108e_01'
  - platform: sp108e_ws2815
    host: 192.168.15.252
    name: 'sp108e_02'
```

But it doesn't work. I couldn't find any light.sp10e_01/2.
